# Generated by Django 6.0.2 on 2026-02-08 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Fan/Yo'nalish")),
                ('description', models.TextField(blank=True, verbose_name="Ta'rif")),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=500, verbose_name='Variant A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Variant B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Variant C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Variant D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('file_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manba fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bilim_sinovi.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sinov nomi')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Davomiyligi (daqiqa)')),
                ('questions_count', models.PositiveIntegerField(default=10, verbose_name='Savollar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilim_sinovi.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Sinov Sozlamasi',
                'verbose_name_plural': 'Sinov Sozlamalari',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Ball')),
                ('correct_answers_count', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqti')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqti')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Javoblar tarixi')),
                ('test_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='bilim_sinovi.testconfig', verbose_name='Sinov')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
            },
        ),
    ]
