# Generated by Django 6.0.1 on 2026-02-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilim_sinovi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconfig',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='Maksimal urinishlar soni'),
        ),
        migrations.AddField(
            model_name='testconfig',
            name='question_order',
            field=models.CharField(choices=[('RANDOM', 'Aralash'), ('SEQUENTIAL', 'Tartib bilan')], default='RANDOM', max_length=20, verbose_name='Savol tartibi'),
        ),
        migrations.AddField(
            model_name='testconfig',
            name='question_sets',
            field=models.ManyToManyField(blank=True, related_name='test_configs', to='bilim_sinovi.subject', verbose_name="Savollar to'plami"),
        ),
    ]
