# Generated by Django 6.0.3 on 2026-03-06 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilim_sinovi', '0002_testconfig_max_attempts_testconfig_question_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bilim_sinovi.subject', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Kategoriya/Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='question_sets',
            field=models.ManyToManyField(blank=True, related_name='test_configs', to='bilim_sinovi.subject', verbose_name='Savol kategoriyalari'),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilim_sinovi.subject', verbose_name='Kategoriya'),
        ),
        migrations.CreateModel(
            name='QuestionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Paket nomi')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Manba fayl')),
                ('parsed_count', models.PositiveIntegerField(default=0, verbose_name="O'qilgan savollar")),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='Saqlangan savollar')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name="O'tkazib yuborilgan savollar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='bilim_sinovi.subject', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_packages', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savollar paketi',
                'verbose_name_plural': 'Savollar paketlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='bilim_sinovi.questionpackage', verbose_name='Paket'),
        ),
        migrations.AddField(
            model_name='testconfig',
            name='question_packages',
            field=models.ManyToManyField(blank=True, related_name='test_configs', to='bilim_sinovi.questionpackage', verbose_name='Savollar paketlari'),
        ),
    ]
