# Generated by Django 6.0.1 on 2026-02-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahalla',
            options={'ordering': ['name'], 'verbose_name': 'Mahalla', 'verbose_name_plural': 'Mahallalar'},
        ),
        migrations.AlterModelOptions(
            name='yosh',
            options={'ordering': ['fullname'], 'verbose_name': 'Yoshlar', 'verbose_name_plural': 'Yoshlar'},
        ),
    ]
