# Generated by Django 6.0.1 on 2026-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mahalla_options_alter_yosh_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahalla',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Mahalla nomi'),
        ),
        migrations.AlterField(
            model_name='yosh',
            name='fullname',
            field=models.CharField(db_index=True, max_length=255, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='yosh',
            name='jshshir',
            field=models.CharField(db_index=True, max_length=14, unique=True, verbose_name='JSHSHIR'),
        ),
        migrations.AlterField(
            model_name='yosh',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pasport raqami'),
        ),
        migrations.AlterField(
            model_name='yosh',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='yosh',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='yoshlar_photos/', verbose_name='Rasm'),
        ),
    ]
