# Generated by Django 6.0.2 on 2026-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mahalla_name_alter_yosh_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sector_coordinator',
            field=models.BooleanField(default=False, verbose_name='Sektor koordinatori'),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1-sektor'), (2, '2-sektor'), (3, '3-sektor'), (4, '4-sektor')], null=True, verbose_name='Sektor'),
        ),
    ]
