# Generated by Django 6.0.2 on 2026-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_sector_coordinator_user_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinfl',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True, verbose_name='PINFL'),
        ),
    ]
