# Generated by Django 6.0.1 on 2026-02-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_pinfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchrashuv',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meetings/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Suhbat rasmi'),
        ),
    ]
