# Generated by Django 6.0.1 on 2026-02-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mutolaa_stats'),
        ('core', '0006_uchrashuv_photo'),
    ]

    operations = []
