# Generated by Django 6.0.1 on 2026-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_about_user_address_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RAHBAR', 'Rahbar'), ('YETAKCHI', 'Yetakchi')], default='YETAKCHI', max_length=20, verbose_name='Rol'),
        ),
    ]
