# Generated by Django 6.0.1 on 2026-02-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(db_index=True)),
                ('date_to', models.DateField(db_index=True)),
                ('block_scores', models.JSONField(blank=True, default=dict)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('debug_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yetakchi KPI snapshot',
                'verbose_name_plural': 'Yetakchi KPI snapshotlar',
                'ordering': ['-date_to', '-created_at'],
                'indexes': [models.Index(fields=['date_from', 'date_to'], name='core_leader_date_fr_74a71e_idx'), models.Index(fields=['user', 'date_to'], name='core_leader_user_id_f36d24_idx')],
                'unique_together': {('user', 'date_from', 'date_to')},
            },
        ),
    ]
