# Generated by Django 6.0.3 on 2026-03-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_yosh_guvohnoma_raqami'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaktabOquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Source ID')),
                ('fullname', models.CharField(db_index=True, max_length=255, verbose_name='F.I.Sh')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Jinsi')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Millati')),
                ('citizenship', models.CharField(blank=True, max_length=100, verbose_name='Fuqaroligi')),
                ('pinfl', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='PINFL')),
                ('document_series', models.CharField(blank=True, max_length=10, verbose_name='Seriya')),
                ('document_number', models.CharField(blank=True, max_length=20, verbose_name='Hujjat raqami')),
                ('organization', models.CharField(db_index=True, max_length=255, verbose_name='Tashkilot')),
                ('organization_region', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Tashkilot hududi')),
                ('klass', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Sinf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_yosh', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_student', to='core.yosh', verbose_name="Bog'langan yosh")),
            ],
            options={
                'verbose_name': "Maktab o'quvchisi",
                'verbose_name_plural': "Maktab o'quvchilari",
                'ordering': ['fullname'],
            },
        ),
    ]
