# Generated by Django 6.0.3 on 2026-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_maktaboquvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='yosh',
            name='school_citizenship',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Maktab fuqaroligi'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_class',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Maktab sinfi'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_document_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Maktab hujjat raqami'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_document_series',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Maktab seriyasi'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_external_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Maktab ID'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_gender',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Maktab jinsi'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Maktab ma'lumoti yuklangan vaqt"),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_nationality',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Maktab millati'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_organization',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Maktab tashkiloti'),
        ),
        migrations.AddField(
            model_name='yosh',
            name='school_organization_region',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Maktab hududi'),
        ),
    ]
