# Generated by Django 6.0.3 on 2026-08-27 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_chat_chatmessage_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiColumnPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_key', models.CharField(max_length=50, verbose_name='Ustun kaliti')),
                ('visible', models.BooleanField(default=True, verbose_name="Ko'rinadimi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_column_prefs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'KPI ustun sozlamasi',
                'verbose_name_plural': 'KPI ustun sozlamalari',
                'ordering': ['column_key'],
                'unique_together': {('user', 'column_key')},
            },
        ),
    ]
