# Generated by Django 6.0.1 on 2026-02-03 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_mahalla_options_alter_yosh_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtaliqLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('organization_type', models.CharField(choices=[('ORGAN', 'Huquq-tartibot organlari'), ('HOKIMLIK', 'Hokimlik'), ('BOSHQA', 'Boshqa tashkilot')], default='ORGAN', max_length=20, verbose_name='Tashkilot turi')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('level', models.CharField(choices=[('TUMAN', 'Tuman darajasi'), ('VILOYAT', 'Viloyat darajasi'), ('RESPUBLIKA', 'Respublika darajasi'), ('OTM', 'OTM')], max_length=20, verbose_name='Darajasi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Soha')),
            ],
            options={
                'verbose_name': 'Otaliq mas’uli',
                'verbose_name_plural': 'Otaliq mas’ullari',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='OtaliqYouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GIYOHVAND', "Giyohvandlar, psixotrop va ularning analoglari hamda spirtli ichimliklarga ruju qo'yganlar"), ('SUDLANGAN', 'Ilgari sudlangan (probatsiya va profilaktik hisobda turmaydiganlar)'), ('JINOYATCHI', 'Jinoyat sodir etgan voyaga yetmaganlar'), ('MJTK_56', "Ma'muriy huquqbuzarlik (MjTK 56-m)"), ('MEHRIBONLIK', 'Mehribonlik uyidan chiqqanlar'), ('PROBATSIYA', 'Probatsiya hisobida'), ('AGRESSIV', 'Agressiv xulq-atvorli yoshlar'), ('YOT_GOYA', "Yot g'oyalar ta'siriga tushib qolganlar")], max_length=100, verbose_name='Toifa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_youths', to='otaliq.otaliqleader', verbose_name='Biriktirilgan rahbar')),
                ('yosh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otaliq_profile', to='core.yosh', verbose_name='Yosh')),
            ],
            options={
                'verbose_name': 'Otaliqqa olingan yosh',
                'verbose_name_plural': 'Otaliqqa olingan yoshlar',
            },
        ),
        migrations.CreateModel(
            name='OtaliqMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(verbose_name='Uchrashuv vaqti')),
                ('photo', models.ImageField(upload_to='otaliq/meetings/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Uchrashuv rasmi')),
                ('description', models.TextField(verbose_name='Uchrashuv mazmuni/izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otaliq_youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='otaliq.otaliqyouth', verbose_name='Otaliq yoshi')),
            ],
            options={
                'verbose_name': 'Otaliq uchrashuvi',
                'verbose_name_plural': 'Otaliq uchrashuvlari',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='OtaliqAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided', models.BooleanField(default=False, verbose_name="Yordam ko'rsatilgan")),
                ('assistance_type', models.CharField(blank=True, choices=[('MODDIY', 'Moddiy yordam'), ('PSIXOLOGIK', "Psixologik ko'mak"), ('ISH', 'Ishga joylashtirish'), ('OQUV', "O'qishga yo'naltirish"), ('TIBBIY', 'Tibbiy yordam'), ('BOSHQA', 'Boshqa yordam')], max_length=50, null=True, verbose_name="Yordam yo'nalishi")),
                ('date_provided', models.DateField(blank=True, null=True, verbose_name="Yordam ko'rsatilgan sana")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Yordam tavsifi')),
                ('document', models.FileField(blank=True, null=True, upload_to='otaliq/assistance_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'rar', 'jpg', 'png'])], verbose_name='Tasdiqlovchi hujjat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otaliq_youth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistance', to='otaliq.otaliqyouth', verbose_name='Otaliq yoshi')),
            ],
            options={
                'verbose_name': "Yordam ma'lumoti",
                'verbose_name_plural': "Yordam ma'lumotlari",
            },
        ),
    ]
