# Generated by Django 6.0.1 on 2026-02-07 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('OGOHLANTIRISH', 'Ogohlantirish'), ('XAYFSAN', 'Xayfsan'), ('ISH_HAQI_30', 'Ish haqidan 30 foiz'), ('ISH_HAQI_50', 'Ish haqidan 50 foiz')], max_length=20, verbose_name='Jazo turi')),
                ('action_date', models.DateField(verbose_name='Jazo sanasi')),
                ('reason', models.TextField(blank=True, verbose_name='Sababi / izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discipline_actions', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan foydalanuvchi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_actions', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Intizomiy jazo',
                'verbose_name_plural': 'Intizomiy jazolar',
                'ordering': ['-action_date', '-created_at'],
            },
        ),
    ]
