# Generated by Django 6.0.1 on 2026-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intizom_jazo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineaction',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AddField(
            model_name='disciplineaction',
            name='resolved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yechilgan sana'),
        ),
        migrations.AddField(
            model_name='disciplineaction',
            name='status',
            field=models.CharField(choices=[('BOR', 'Bor'), ('YECHILGAN', 'Yechilgan')], default='BOR', max_length=10, verbose_name='Joriy holati'),
        ),
    ]
