# Generated by Django 6.0.1 on 2026-02-01 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('level', models.CharField(choices=[('TUMAN', 'Tuman darajasi'), ('VILOYAT', 'Viloyat darajasi'), ('RESPUBLIKA', 'Respublika darajasi'), ('ALOHIDA', 'Alohida')], max_length=20, verbose_name='Darajasi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tashkilot nomi')),
            ],
            options={
                'verbose_name': 'Mas’ul rahbar',
                'verbose_name_plural': 'Mas’ul rahbarlar',
            },
        ),
        migrations.CreateModel(
            name='UnemployedYouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MODDIY', 'Moddiy yordamga muhtoj'), ('SOGLIK', 'Sog‘ligida muammosi bor'), ('ISHSiz', 'Ishsiz'), ('BOSHQA', 'Boshqa')], max_length=100, verbose_name='Ishsizlik kategoriyasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_youths', to='ishsiz_yoshlar.responsibleleader', verbose_name='Mas’ul rahbar')),
                ('yosh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unemployed_profile', to='core.yosh', verbose_name='Yosh')),
            ],
            options={
                'verbose_name': 'Ishsiz yosh',
                'verbose_name_plural': 'Ishsiz yoshlar',
            },
        ),
        migrations.CreateModel(
            name='AssistanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided', models.BooleanField(default=False, verbose_name="Yordam ko'rsatilgan")),
                ('assistance_type', models.CharField(blank=True, choices=[('BANDLIK', 'Bandlikni ta’minlash'), ('TADBIRKORLIK', 'Tadbirkorlikka yo‘naltirish'), ('KASB_HUNAR', 'Kasb-hunarga o‘qitish'), ('MODDIY', 'Moddiy yordam'), ('SUBSIDIYA', 'Subsidiya ajratish'), ('KREDIT', 'Imtiyozli kredit'), ('BOSHQA', 'Boshqa')], max_length=50, null=True, verbose_name="Yordam yo'nalishi")),
                ('date_provided', models.DateField(blank=True, null=True, verbose_name="Yordam ko'rsatilgan sana")),
                ('document', models.FileField(blank=True, null=True, upload_to='assistance_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Tasdiqlovchi hujjat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unemployed_youth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistance', to='ishsiz_yoshlar.unemployedyouth', verbose_name='Ishsiz yosh')),
            ],
            options={
                'verbose_name': "Yordam ma'lumoti",
                'verbose_name_plural': "Yordam ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='YouthMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(verbose_name='Uchrashuv vaqti')),
                ('photo', models.ImageField(upload_to='meetings/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Uchrashuv rasmi')),
                ('description', models.TextField(verbose_name='Uchrashuv mazmuni/izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unemployed_youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='ishsiz_yoshlar.unemployedyouth', verbose_name='Ishsiz yosh')),
            ],
            options={
                'verbose_name': 'Uchrashuv',
                'verbose_name_plural': 'Uchrashuvlar',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.AddIndex(
            model_name='unemployedyouth',
            index=models.Index(fields=['category'], name='ishsiz_yosh_categor_267b78_idx'),
        ),
        migrations.AddIndex(
            model_name='unemployedyouth',
            index=models.Index(fields=['leader'], name='ishsiz_yosh_leader__cc97d6_idx'),
        ),
    ]
