# Generated by Django 6.0.1 on 2026-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibleleader',
            options={'ordering': ['full_name'], 'verbose_name': 'Mas’ul rahbar', 'verbose_name_plural': 'Mas’ul rahbarlar'},
        ),
        migrations.AlterField(
            model_name='unemployedyouth',
            name='category',
            field=models.CharField(choices=[('MIGRATSIYA', 'Migratsiyadan qaytgan ishsizlar'), ('MAKTAB', 'Maktab'), ('KASBIY', 'Kasbiy ta’lim'), ('OLIY', 'Oliy ta’lim'), ('QOLGAN', 'Qolgan ishsizlar')], max_length=100, verbose_name='Toifa'),
        ),
    ]
