# Generated by Django 6.0.1 on 2026-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0002_alter_responsibleleader_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibleleader',
            name='level',
            field=models.CharField(choices=[('TUMAN', 'Tuman darajasi'), ('VILOYAT', 'Viloyat darajasi'), ('RESPUBLIKA', 'Respublika darajasi'), ('OTM', 'OTM')], max_length=20, verbose_name='Darajasi'),
        ),
    ]
