# Generated by Django 6.0.1 on 2026-02-01 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0003_alter_responsibleleader_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleleader',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soha'),
        ),
        migrations.AlterField(
            model_name='assistanceinfo',
            name='assistance_type',
            field=models.CharField(blank=True, choices=[('ISH', 'Doimiy ishga joylashgan'), ('KREDIT', 'Tadbirkorlik va kredit'), ('MIGRATSIYA', 'Tartibli migratsiya'), ('YER', 'Ekin yer maydoni'), ('SUBSIDIYA', 'Asbob-uskuna ajratilgan'), ('BOSHQA', 'Boshqa')], max_length=50, null=True, verbose_name="Yordam yo'nalishi"),
        ),
        migrations.AlterField(
            model_name='assistanceinfo',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='assistance_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'rar'])], verbose_name='Tasdiqlovchi hujjat'),
        ),
    ]
