# Generated by Django 6.0.1 on 2026-02-03 18:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mahalla_name_alter_yosh_fullname_and_more'),
        ('ishsiz_yoshlar', '0004_responsibleleader_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibleleader',
            options={'ordering': ['full_name'], 'verbose_name': "Mas'ul rahbar", 'verbose_name_plural': "Mas'ul rahbarlar"},
        ),
        migrations.AlterField(
            model_name='unemployedyouth',
            name='category',
            field=models.CharField(choices=[('MIGRATSIYA', 'Migratsiyadan qaytgan ishsizlar'), ('MAKTAB', 'Maktab'), ('KASBIY', "Kasbiy ta'lim"), ('OLIY', "Oliy ta'lim"), ('QOLGAN', 'Qolgan ishsizlar')], db_index=True, max_length=100, verbose_name='Toifa'),
        ),
        migrations.AlterField(
            model_name='unemployedyouth',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='unemployedyouth',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_youths', to='ishsiz_yoshlar.responsibleleader', verbose_name="Mas'ul rahbar"),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Topshiriq nomi')),
                ('description', models.TextField(verbose_name='Topshiriq tavsifi')),
                ('status', models.CharField(choices=[('YANGI', 'Yangi'), ('BAJARILMOQDA', 'Bajarilmoqda'), ('TASDIQLANGAN', 'Tasdiqlangan'), ('RAD_ETILGAN', 'Rad etilgan'), ('YAKUNLANGAN', 'Yakunlangan')], default='YANGI', max_length=20, verbose_name='Holati')),
                ('priority', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('URGENT', 'Shoshilinch')], default='MEDIUM', max_length=10, verbose_name='Muhimlik')),
                ('due_date', models.DateTimeField(verbose_name='Bajarish muddati')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip'])], verbose_name='Biriktirilgan fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ijro uchun topshirilgan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan admin')),
                ('target_mahalla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.mahalla', verbose_name="Mo'ljaldagi mahalla")),
                ('target_youth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.yosh', verbose_name="Mo'ljaldagi yosh")),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_CREATED', 'Topshiriq yaratildi'), ('TASK_UPDATED', 'Topshiriq yangilandi'), ('TASK_RESPONSE', 'Javob qabul qilindi'), ('TASK_COMPLETED', 'Topshiriq yakunlandi'), ('TASK_OVERDUE', "Topshiriq muddati o'tgan")], max_length=20, verbose_name='Xabar turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ishsiz_yoshlar.task', verbose_name='Topshiriq')),
            ],
            options={
                'verbose_name': 'Topshiriq xabari',
                'verbose_name_plural': 'Topshiriq xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('QABUL_QILDIM', 'Qabul qildim'), ('RAD_ETDIM', 'Rad etdim'), ('BAJARILDI', 'Bajarildi'), ('MUAMMO_BOR', 'Muamm bor')], max_length=20, verbose_name='Javob turi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('completion_file', models.FileField(blank=True, null=True, upload_to='task_completions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip'])], verbose_name='Bajarilgan ishing fayli')),
                ('responded_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ishsiz_yoshlar.task', verbose_name='Topshiriq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_responses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Topshiriq javobi',
                'verbose_name_plural': 'Topshiriq javoblari',
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='ishsiz_yosh_status_b2103f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='ishsiz_yosh_priorit_61e7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='ishsiz_yosh_due_dat_46f59c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='ishsiz_yosh_assigne_5a3582_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['recipient', 'is_read'], name='ishsiz_yosh_recipie_632f7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskresponse',
            unique_together={('task', 'user')},
        ),
    ]
