# Generated by Django 6.0.2 on 2026-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0005_alter_responsibleleader_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('YANGI', 'Yangi'), ('BAJARILMOQDA', 'Bajarilmoqda'), ('TASDIQLANGAN', 'Tekshirilmoqda'), ('RAD_ETILGAN', 'Rad etilgan'), ('YAKUNLANGAN', 'Yakunlangan')], default='YANGI', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_CREATED', 'Topshiriq yaratildi'), ('TASK_UPDATED', 'Topshiriq yangilandi'), ('TASK_RESPONSE', 'Javob qabul qilindi'), ('TASK_COMPLETED', 'Topshiriq yakunlandi'), ('TASK_OVERDUE', "Topshiriq muddati o'tgan"), ('TASK_RETURNED', 'Topshiriq qaytarildi'), ('TASK_APPROVED', 'Topshiriq tasdiqlandi')], max_length=20, verbose_name='Xabar turi'),
        ),
    ]
