# Generated by Django 6.0.2 on 2026-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0008_task_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='ishsiz_yosh_task_gr_3e8d78_idx',
            old_name='ishsiz_yos_task_gr_3c0a1e_idx',
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
