# Generated by Django 6.0.1 on 2026-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0010_cleanup_assistance_type_boshqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceinfo',
            name='assistance_type',
            field=models.CharField(blank=True, choices=[('ISH', 'Doimiy ishga joylashgan'), ('KREDIT', 'Tadbirkorlik uchun kredit ajratilgan'), ('MIGRATSIYA', 'Tartibli migratsiyaga yuborilgan'), ('YER', 'Ekin yer maydoni ajratilgan'), ('SUBSIDIYA', 'Asbob-uskuna ajratilgan')], max_length=50, null=True, verbose_name="Yordam yo'nalishi"),
        ),
    ]
