# Generated by Django 6.0.3 on 2026-08-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_yosh_school_citizenship_yosh_school_class_and_more'),
        ('ishsiz_yoshlar', '0011_alter_assistanceinfo_assistance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unemployedyouth',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2025, '2025'), (2026, '2026')], db_index=True, default=2025, verbose_name='Yil'),
        ),
        migrations.AddIndex(
            model_name='unemployedyouth',
            index=models.Index(fields=['year'], name='ishsiz_yosh_year_bc2b85_idx'),
        ),
    ]
