# Generated by Django 6.0.3 on 2026-08-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0013_set_existing_data_to_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='unemployedyouth',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name="Yo'nalish"),
        ),
        migrations.AddField(
            model_name='unemployedyouth',
            name='otm_name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='OTM nomi'),
        ),
    ]
