# Generated by Django 6.0.3 on 2026-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishsiz_yoshlar', '0014_unemployedyouth_direction_unemployedyouth_otm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployedyouth',
            name='otm_name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name="Ta'lim tashkiloti"),
        ),
    ]
