# Generated by Django 6.0.3 on 2026-08-19 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_yosh_school_citizenship_yosh_school_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_installed', models.BooleanField(default=False, verbose_name="O'rnatilgan")),
                ('capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quvvat (kVt)')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name="O'rnatilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('mahalla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_panel', to='core.mahalla', verbose_name='Mahalla')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Quyosh paneli',
                'verbose_name_plural': 'Quyosh panellari',
                'ordering': ['mahalla__name'],
            },
        ),
    ]
