# Generated by Django 6.0.1 on 2026-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beshtashabbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiveinitiativeevent',
            name='direction',
            field=models.CharField(choices=[('SPORT', 'Sport'), ('KASB', 'Kasblar tanlovi'), ('KITOB', 'Kitobxonlik'), ('SANAT', "San'at va madaniyat"), ('INTEL', "Intelektual o'yinlar"), ('KIBER', 'Kibersport')], max_length=20, verbose_name="Tadbir yo'nalishi"),
        ),
    ]
