# Generated by Codex on 2026-02-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_leaderkpisnapshot'),
        ('beshtashabbus', '0002_alter_fiveinitiativeevent_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveInitiativeApplicationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, default=2026, verbose_name='Yil')),
                ('source_file_name', models.CharField(max_length=255, verbose_name='Yuklangan fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuklangan vaqt')),
                ('raw_meta', models.JSONField(blank=True, default=dict, verbose_name='Import meta')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five_initiative_application_snapshots', to='core.user', verbose_name="Yuklagan foydalanuvchi")),
            ],
            options={
                'verbose_name': '5 tashabbus ariza snapshoti',
                'verbose_name_plural': '5 tashabbus ariza snapshotlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiveInitiativeApplicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', max_length=150, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, default='', max_length=150, verbose_name='Tuman')),
                ('sector', models.CharField(blank=True, default='', max_length=150, verbose_name='Sektor')),
                ('mahalla_name_raw', models.CharField(max_length=255, verbose_name='Mahalla (xom)')),
                ('participant_name', models.CharField(max_length=255, verbose_name='Ishtirokchi F.I.O')),
                ('pinfl', models.CharField(db_index=True, max_length=14, verbose_name='PINFL')),
                ('gender', models.CharField(blank=True, default='', max_length=30, verbose_name='Jinsi')),
                ('age_category', models.CharField(blank=True, default='', max_length=80, verbose_name='Yosh toifasi')),
                ('selection_category', models.CharField(db_index=True, max_length=120, verbose_name='Kategoriya')),
                ('direction', models.CharField(db_index=True, max_length=120, verbose_name="Yo'nalish")),
                ('mahalla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five_initiative_application_entries', to='core.mahalla', verbose_name='Mahalla')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='beshtashabbus.fiveinitiativeapplicationsnapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': '5 tashabbus ariza qatori',
                'verbose_name_plural': '5 tashabbus ariza qatorlari',
                'ordering': ['mahalla_name_raw', 'participant_name'],
                'indexes': [
                    models.Index(fields=['snapshot', 'mahalla'], name='beshtashabb_snapsho_5afd44_idx'),
                    models.Index(fields=['snapshot', 'selection_category'], name='beshtashabb_snapsho_9fa3a4_idx'),
                    models.Index(fields=['snapshot', 'direction'], name='beshtashabb_snapsho_275d26_idx'),
                    models.Index(fields=['snapshot', 'pinfl'], name='beshtashabb_snapsho_b2ee32_idx'),
                ],
            },
        ),
    ]
