# Generated by Django 6.0.3 on 2026-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beshtashabbus', '0004_application_entry_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveInitiativeSvodNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_category', models.CharField(max_length=150, verbose_name='Kategoriya')),
                ('direction', models.CharField(max_length=150, verbose_name="Yo'nalish")),
                ('age_category', models.CharField(max_length=100, verbose_name='Yosh toifasi')),
                ('gender', models.CharField(blank=True, default='', help_text="Bo'sh bo'lsa erkak+ayol qo'shiladi", max_length=30, verbose_name='Jinsi')),
                ('norma', models.PositiveIntegerField(default=0, verbose_name='Norma')),
                ('row_order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': '5 tashabbus svod norma',
                'verbose_name_plural': '5 tashabbus svod normalari',
                'ordering': ['row_order', 'selection_category', 'direction'],
                'unique_together': {('selection_category', 'direction', 'age_category', 'gender')},
            },
        ),
    ]
