# Generated by Django 6.0.1 on 2026-02-05

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_user_pinfl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('HOKIMIYAT', 'Hokimiyatdagi majlis'), ('SEMINAR', 'Seminar'), ('RAHBAR', 'Rahbar majlisi'), ('YUQORI', 'Yuqori idoralar majlisi'), ('ZOOM', 'Zoom/Videochat majlisi'), ('YIGILISH', "Yig'ilish"), ('BOSHQA', 'Boshqa')], max_length=20, verbose_name="Yo'qlama turi")),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Sababi/Izoh')),
                ('session_date', models.DateTimeField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': "Yo'qlama",
                'verbose_name_plural': "Yo'qlamalar",
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ON_TIME', 'Vaqtida qatnashdi'), ('LATE', 'Kechikib qatnashdi'), ('EXCUSED', 'Sababli qatnasha olmadi'), ('UNEXCUSED', 'Sababsiz qatnasha olmadi'), ('NA', 'Tegishli emas')], max_length=20, null=True, verbose_name='Holati')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Sababi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Yetakchi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='yoqlama.attendancesession', verbose_name="Yo'qlama")),
            ],
            options={
                'verbose_name': "Yo'qlama yozuvi",
                'verbose_name_plural': "Yo'qlama yozuvlari",
                'ordering': ['leader__full_name'],
                'unique_together': {('session', 'leader')},
            },
        ),
    ]
