# Generated by Django 6.0.1 on 2026-02-04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_user_pinfl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationYouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Chiqib ketgan sana')),
                ('destination_country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('destination_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsiya')),
                ('destination_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('reason', models.CharField(choices=[('DAM_OLISH', 'Dam olish'), ('ISH', 'Ish'), ('TALIM', "Ta'lim olish"), ('DAVOLANISH', 'Davolanish'), ('YASHASH', 'Yashash')], max_length=20, verbose_name='Chiqib ketish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('yosh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='migration_profile', to='core.yosh', verbose_name='Yosh')),
            ],
            options={
                'verbose_name': 'Migratsiyadagi yosh',
                'verbose_name_plural': 'Migratsiyadagi yoshlar',
            },
        ),
        migrations.CreateModel(
            name='MigrationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(verbose_name='Suhbat vaqti')),
                ('photo', models.ImageField(upload_to='migratsiya/meetings/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Suhbat rasmi yoki skrinshoti')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Qachon qaytmoqchi')),
                ('work_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qanday ishda ishlaydi')),
                ('work_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Qancha pul topadi (oylik)')),
                ('work_conditions_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ish sharoiti (1-10)')),
                ('education_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qaysi dargohda')),
                ('education_direction', models.CharField(blank=True, max_length=255, null=True, verbose_name="Qaysi yo'nalishda")),
                ('education_course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nechanchi kurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migration_youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='migratsiya.migrationyouth', verbose_name='Migratsiyadagi yosh')),
            ],
            options={
                'verbose_name': 'Suhbat',
                'verbose_name_plural': 'Suhbatlar',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
