# Generated by Django 6.0.1 on 2026-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migratsiya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationmeeting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
    ]
