# Generated by Django 6.0.1 on 2026-02-04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_user_pinfl'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tadbir nomi')),
                ('event_date', models.DateField(verbose_name='Sana')),
                ('event_type', models.CharField(choices=[('TIG', "Tig' reydi"), ('TUNGI', 'Tungi reyd'), ('BOSHQA', 'Boshqa reyd')], default='BOSHQA', max_length=20, verbose_name='Reyd turi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reyd_events', to='core.mahalla', verbose_name='Mahalla')),
            ],
            options={
                'verbose_name': 'Reyd tadbiri',
                'verbose_name_plural': 'Reyd tadbirlari',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaidPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reyd/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reyd.raidevent', verbose_name='Reyd tadbiri')),
            ],
            options={
                'verbose_name': 'Reyd rasmi',
                'verbose_name_plural': 'Reyd rasmlari',
            },
        ),
    ]
