# Generated by Django 6.0.3 on 2026-03-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_yosh_school_citizenship_yosh_school_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EkinYerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255, verbose_name='Manba fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuklangan vaqt')),
                ('raw_meta', models.JSONField(blank=True, default=dict, verbose_name='Import meta')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ekin_yer_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ekin yerlari snapshot',
                'verbose_name_plural': 'Ekin yerlari snapshotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EkinYerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entry_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Source ID')),
                ('winner_external_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name="G'olib source ID")),
                ('winner_name', models.CharField(db_index=True, max_length=255, verbose_name='F.I.Sh')),
                ('winner_name_normalized', models.CharField(db_index=True, max_length=255, verbose_name='F.I.Sh (norm)')),
                ('winner_birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name="Tug'ilgan sana")),
                ('winner_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon')),
                ('winner_neighborhood_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Yashash mahallasi')),
                ('land_neighborhood_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Yer mahalla ID')),
                ('land_neighborhood_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Yer mahallasi')),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maydon')),
                ('area_specialization', models.CharField(blank=True, default='', max_length=255, verbose_name="Yo'nalish")),
                ('specialty_category', models.CharField(blank=True, default='', max_length=255, verbose_name='Kategoriya')),
                ('specialty_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Ekin turi')),
                ('contour_numbers', models.JSONField(blank=True, default=list, verbose_name='Konturlar')),
                ('land_type', models.JSONField(blank=True, default=list, verbose_name='Yer turi')),
                ('geometry', models.JSONField(blank=True, default=dict, verbose_name='Geometriya')),
                ('location', models.JSONField(blank=True, default=dict, verbose_name='Joylashuv')),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='Xom yozuv')),
                ('match_status', models.CharField(choices=[('MATCHED', 'Topildi'), ('AMBIGUOUS', 'Noaniq'), ('NOT_FOUND', 'Topilmadi')], db_index=True, default='NOT_FOUND', max_length=20, verbose_name='Moslash holati')),
                ('match_note', models.CharField(blank=True, default='', max_length=255, verbose_name='Moslash izohi')),
                ('possible_matches', models.JSONField(blank=True, default=list, verbose_name='Ehtimoliy mosliklar')),
                ('is_youth_age', models.BooleanField(db_index=True, default=False, verbose_name='Yosh toifasida')),
                ('linked_yosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ekin_yer_entries', to='core.yosh', verbose_name="Bog'langan yosh")),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ekin_yerlari.ekinyersnapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Ekin yer yozuvi',
                'verbose_name_plural': 'Ekin yer yozuvlari',
                'ordering': ['land_neighborhood_name', 'winner_name'],
                'indexes': [models.Index(fields=['snapshot', 'match_status'], name='ekin_yerlar_snapsho_6b7dae_idx'), models.Index(fields=['snapshot', 'linked_yosh'], name='ekin_yerlar_snapsho_79a317_idx'), models.Index(fields=['snapshot', 'land_neighborhood_name'], name='ekin_yerlar_snapsho_31ce05_idx')],
            },
        ),
    ]
