# Generated by Django 6.0.3 on 2026-03-26 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Savol matni')),
                ('question_type', models.CharField(choices=[('short_text', 'Qisqa matn (text)'), ('long_text', 'Uzun matn (textarea)'), ('number', 'Son (number)'), ('date', 'Sana (date)'), ('radio', 'Radio tugma (bitta tanlov)'), ('checkbox', "Checkbox (ko'p tanlov)"), ('select', "Ochiluvchi ro'yxat (select)"), ('buttons', 'Tanlanadigan tugmalar'), ('image', 'Rasm (image)'), ('file', 'Fayl (file)')], max_length=20, verbose_name='Savol turi')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiymi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Ta'rifi")),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('paused', "To'xtatilgan"), ('completed', 'Tugallangan')], default='active', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Variant matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sorovnoma.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sorovnoma.survey', verbose_name="So'rovnoma")),
            ],
            options={
                'verbose_name': "Javob (So'rovnoma natijasi)",
                'verbose_name_plural': "Javoblar (So'rovnoma natijalari)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Matnli javob')),
                ('file_body', models.FileField(blank=True, null=True, upload_to='survey_files/', verbose_name='Fayl/Rasm javob')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sorovnoma.question', verbose_name='Savol')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sorovnoma.response', verbose_name="So'rovnoma natijasi")),
            ],
            options={
                'verbose_name': 'Savolga javob',
                'verbose_name_plural': 'Savollarga javoblar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sorovnoma.survey', verbose_name="So'rovnoma"),
        ),
    ]
