# Generated by Django 6.0.3 on 2026-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorovnoma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices_text',
            field=models.TextField(blank=True, help_text='Faqat tanlovli savollar uchun. Har bir variantni yangi qatordan yozing (Enter bosib).', null=True, verbose_name='Variantlar'),
        ),
    ]
