# Generated by Django 6.0.3 on 2026-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorovnoma', '0002_question_choices_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_in_list',
            field=models.BooleanField(default=False, help_text="Belgilansa, ushbu savol javobi 'Barcha natijalar' jadvalida alohida ustun bo'lib chiqadi.", verbose_name="Natijalar ro'yxatida ustun sifatida ko'rsatish"),
        ),
    ]
