# Generated by Django 6.0.3 on 2026-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorovnoma', '0003_question_show_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_edit',
            field=models.BooleanField(default=False, help_text='Tahrirlash imkoni', verbose_name='Javobni tahrirlash'),
        ),
        migrations.AddField(
            model_name='survey',
            name='allow_multi',
            field=models.BooleanField(default=False, help_text="Belgilansa tahrirlash emas yangidan javob yaratish mumkin bo'ladi.", verbose_name="Qayta to'ldirish"),
        ),
    ]
