# Generated by Django 6.0.3 on 2026-03-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorovnoma', '0004_survey_allow_edit_survey_allow_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, default='', help_text="Bir xil bo'lim nomini yozsangiz savollar guruhlanadi.", max_length=255, verbose_name="Bo'lim"),
        ),
    ]
